/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jtdev_jfilenotify_inotify_INotifyService */

#ifndef _Included_de_jtdev_jfilenotify_inotify_INotifyService
#define _Included_de_jtdev_jfilenotify_inotify_INotifyService
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: threadInitNumber */
/* Inaccessible static: threadSeqNumber */
#undef de_jtdev_jfilenotify_inotify_INotifyService_MIN_PRIORITY
#define de_jtdev_jfilenotify_inotify_INotifyService_MIN_PRIORITY 1L
#undef de_jtdev_jfilenotify_inotify_INotifyService_NORM_PRIORITY
#define de_jtdev_jfilenotify_inotify_INotifyService_NORM_PRIORITY 5L
#undef de_jtdev_jfilenotify_inotify_INotifyService_MAX_PRIORITY
#define de_jtdev_jfilenotify_inotify_INotifyService_MAX_PRIORITY 10L
/* Inaccessible static: EMPTY_STACK_TRACE */
/* Inaccessible static: SUBCLASS_IMPLEMENTATION_PERMISSION */
/* Inaccessible static: subclassAudits */
/* Inaccessible static: defaultUncaughtExceptionHandler */
/*
 * Class:     de_jtdev_jfilenotify_inotify_INotifyService
 * Method:    createINotifyInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_jtdev_jfilenotify_inotify_INotifyService_createINotifyInstance
  (JNIEnv *, jobject);

/*
 * Class:     de_jtdev_jfilenotify_inotify_INotifyService
 * Method:    releaseINotifyInstance
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_jtdev_jfilenotify_inotify_INotifyService_releaseINotifyInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jtdev_jfilenotify_inotify_INotifyService
 * Method:    addWatch
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_de_jtdev_jfilenotify_inotify_INotifyService_addWatch
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     de_jtdev_jfilenotify_inotify_INotifyService
 * Method:    removeWatch
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_jtdev_jfilenotify_inotify_INotifyService_removeWatch
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_jtdev_jfilenotify_inotify_INotifyService
 * Method:    readEventData
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_jtdev_jfilenotify_inotify_INotifyService_readEventData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_jtdev_jfilenotify_inotify_INotifyService
 * Method:    getIntegerSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_jtdev_jfilenotify_inotify_INotifyService_getIntegerSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
